<?php

return [
    'tagline' => 'Street Light Ads | Pavement Ads | Bill Boards',
    'introduction' => 'Welcome to Effective Media marketing agency. We help brands leverage outdoor advertising through street light boxes, also referred to as street pole kiosk branding.',
    'about' => [
        'company' => 'Effective Media is a #1 marketing agency focused on practical outdoor visibility. We deploy compact billboard boxes on electric poles, back-to-back, across major city roads to build repetitive brand remembrance.',
        'vision' => 'To remain the most efficient and impressionable outdoor advertising partner for repetitive branding across Kenyan towns and highways.',
        'mission' => 'Enable brands to gain guaranteed exposure in high-traffic locations using cost-effective street light box, pavement, billboard, and branding solutions.',
        'goals' => [
            'Guarantee exposure in high-traffic locations.',
            'Deliver crisp and clean print output on every campaign.',
            'Expand coverage through strategically placed poles and partner media.',
            'Maintain campaign quality through routine cleaning and maintenance.',
        ],
        'values' => [
            'Reliability',
            'Cost effectiveness',
            'Speed of replacement and re-targeting',
            'Quality print production',
            'Consistent campaign maintenance',
        ],
        'story_timeline' => [
            ['period' => '2006', 'title' => 'Foundation', 'detail' => 'Effective Media was founded to solve local visibility gaps using practical outdoor branding infrastructure.'],
            ['period' => '2010+', 'title' => 'Street Light Network Growth', 'detail' => 'Expanded from local installations to structured street light box deployment on key urban and highway corridors.'],
            ['period' => 'Regional Expansion', 'title' => 'Multi-County Reach', 'detail' => 'Scaled operations across major towns including Nakuru, Kisumu, Eldoret, Naivasha, Gilgil, Nanyuki, and more.'],
            ['period' => 'Today', 'title' => 'Campaign Intelligence Focus', 'detail' => 'Combines field infrastructure, responsive maintenance, and planning workflows for confidence-driven campaign delivery.'],
        ],
    ],
    'services' => [
        'Outdoor advertising, majorly streetlight',
        'Street Light Box Advertising',
        'Pavement Ads',
        'Billboards',
        'Roll-up banners & tear drops',
        'Product launches & activations',
        'Advertising & promotions',
        'Road shows & merchandising',
        'Office branding',
    ],
    'service_details' => [
        'Outdoor advertising, majorly streetlight' => [
            'description' => 'Core outdoor media offering focused on high-traffic street light corridors for repetitive visibility and market recall.',
            'image' => 'profile-page-2.jpg',
        ],
        'Street Light Box Advertising' => [
            'description' => 'Compact advertising billboards mounted back-to-back on electric poles along major roads to maximize repeated impressions.',
            'image' => 'profile-page-3.jpg',
        ],
        'Pavement Ads' => [
            'description' => 'Street-level visibility placements in pedestrian and commuter zones for direct local audience contact.',
            'image' => 'profile-page-4.jpg',
        ],
        'Billboards' => [
            'description' => 'Large-format supporting media used with street light boxes to expand campaign reach and urban dominance.',
            'image' => 'profile-page-5.jpg',
        ],
        'Roll-up banners & tear drops' => [
            'description' => 'Event and activation support collateral for onsite awareness, launches, and directional branding.',
            'image' => 'profile-page-6.jpg',
        ],
        'Product launches & activations' => [
            'description' => 'Field activation campaigns with tactical media support to boost product discovery and engagement.',
            'image' => 'profile-page-7.jpg',
        ],
        'Advertising & promotions' => [
            'description' => 'Integrated promotion support across outdoor placements and campaign execution workflows.',
            'image' => 'profile-page-8.jpg',
        ],
        'Road shows & merchandising' => [
            'description' => 'On-ground brand visibility operations combining mobile exposure, point branding, and sales-driven presence.',
            'image' => 'profile-page-5.jpg',
        ],
        'Office branding' => [
            'description' => 'Interior and exterior office visual branding solutions aligned to brand identity and customer experience.',
            'image' => 'profile-page-6.jpg',
        ],
    ],
    'street_light_box' => [
        'explanation' => 'Street Light Box Advertising comprises putting up small and compact advertising billboards on electric poles, back to back in a row on major city roads.',
        'benefits' => [
            'Guaranteed exposure in high-traffic locations.',
            'Cost-effective repetitive advertising.',
            'Different messages can run on different boxes.',
            'Can be placed anywhere as long as there are poles.',
            'Repetition creates remembrance.',
        ],
        'process' => [
            'Identify your sites.',
            'Get a quote.',
            'Choose your dates.',
            'Send approved artwork to info@effectivemedia.co.ke.',
            'Campaign setup with cleaning and maintenance twice a month.',
        ],
    ],
    'reach' => [
        ['county' => 'Nakuru', 'site' => 'Kenyatta Ave', 'poles' => 30],
        ['county' => 'Nakuru', 'site' => 'West Rd', 'poles' => 12],
        ['county' => 'Nakuru', 'site' => 'Njoro Interchange', 'poles' => 60],
        ['county' => 'Nakuru', 'site' => 'Club Rd', 'poles' => 6],
        ['county' => 'Nakuru', 'site' => 'Kijabe Rd', 'poles' => 15],
        ['county' => 'Nakuru', 'site' => 'Mburu Gichua Rd', 'poles' => 5],
        ['county' => 'Nakuru', 'site' => 'Sobea Town', 'poles' => 15],
        ['county' => 'Nakuru', 'site' => 'Salgaa Town', 'poles' => 20],
        ['county' => 'Nakuru', 'site' => '58 Interchange', 'poles' => 40],
        ['county' => 'Nakuru', 'site' => 'Total Interchange', 'poles' => 100],
        ['county' => 'Nakuru', 'site' => 'Nyahururu Town', 'poles' => 70],
        ['county' => 'Nakuru', 'site' => 'Kabarak Town', 'poles' => 20],
        ['county' => 'Nakuru', 'site' => 'Pipeline/Barnabas', 'poles' => 25],
        ['county' => 'Nakuru', 'site' => 'CBD', 'poles' => 20],
        ['county' => 'Gilgil', 'site' => 'CBD', 'poles' => 20],
        ['county' => 'Gilgil', 'site' => 'Highway', 'poles' => 2],
        ['county' => 'Naivasha', 'site' => 'CBD', 'poles' => 20],
        ['county' => 'Eldoret', 'site' => 'Uganda Rd', 'poles' => 10],
        ['county' => 'Eldoret', 'site' => 'Rupu Mall', 'poles' => 10],
        ['county' => 'Eldoret', 'site' => 'Itemi Rd', 'poles' => 20],
        ['county' => 'Eldoret', 'site' => 'Kisumu Rd', 'poles' => 20],
        ['county' => 'Eldoret', 'site' => 'Elgon View', 'poles' => 10],
        ['county' => 'Kisumu', 'site' => 'Nairobi Rd', 'poles' => 20],
        ['county' => 'Kisumu', 'site' => 'Busia Rd', 'poles' => 20],
        ['county' => 'Kisumu', 'site' => 'Kakamega Rd', 'poles' => 20],
        ['county' => 'Kisumu', 'site' => 'Kiladure Rd', 'poles' => 20],
        ['county' => 'Kisumu', 'site' => 'CBD', 'poles' => 10],
        ['county' => 'Nanyuki', 'site' => 'Kenyatta Street', 'poles' => 20],
        ['county' => 'Kisii', 'site' => 'CBD', 'poles' => 30],
        ['county' => 'Kisii', 'site' => 'Kisumu Rd', 'poles' => 20],
        ['county' => 'Kisii', 'site' => 'Nyamira Rd', 'poles' => 10],
        ['county' => 'Kisii', 'site' => 'Keroka Rd', 'poles' => 10],
    ],
    'coverage_towns' => ['Narok', 'Kericho', 'Kakamega', 'Kitale', 'Bungoma', 'Lodwar', 'Garissa', 'Wajir', 'Marsabit', 'Meru', 'Embu', 'Machakos', 'Kitui', 'Kitengela', 'Kajiado', 'Kilifi', 'Bomet', 'Laikipia'],
    // Approximate town coordinates for coverage visualization.
    // TODO: replace with exact GPS coordinates from backend-managed site records.
    'coverage_map_points' => [
        ['town' => 'Nakuru', 'county' => 'Nakuru', 'lat' => -0.3031, 'lng' => 36.0800, 'media_type' => 'Street Light Ads'],
        ['town' => 'Gilgil', 'county' => 'Nakuru', 'lat' => -0.5000, 'lng' => 36.3167, 'media_type' => 'Street Light Ads'],
        ['town' => 'Naivasha', 'county' => 'Nakuru', 'lat' => -0.7167, 'lng' => 36.4333, 'media_type' => 'Pavement Ads'],
        ['town' => 'Kisumu', 'county' => 'Kisumu', 'lat' => -0.1022, 'lng' => 34.7617, 'media_type' => 'Street Light Ads'],
        ['town' => 'Eldoret', 'county' => 'Uasin Gishu', 'lat' => 0.5143, 'lng' => 35.2698, 'media_type' => 'Street Light Ads'],
        ['town' => 'Nanyuki', 'county' => 'Laikipia', 'lat' => 0.0167, 'lng' => 37.0667, 'media_type' => 'Street Light Ads'],
        ['town' => 'Kericho', 'county' => 'Kericho', 'lat' => -0.3670, 'lng' => 35.2831, 'media_type' => 'Billboards'],
        ['town' => 'Bomet', 'county' => 'Bomet', 'lat' => -0.7813, 'lng' => 35.3416, 'media_type' => 'Street Light Ads'],
        ['town' => 'Narok', 'county' => 'Narok', 'lat' => -1.0853, 'lng' => 35.8711, 'media_type' => 'Street Light Ads'],
        ['town' => 'Kitale', 'county' => 'Trans Nzoia', 'lat' => 1.0157, 'lng' => 35.0062, 'media_type' => 'Street Light Ads'],
        ['town' => 'Bungoma', 'county' => 'Bungoma', 'lat' => 0.5635, 'lng' => 34.5606, 'media_type' => 'Pavement Ads'],
        ['town' => 'Garissa', 'county' => 'Garissa', 'lat' => -0.4536, 'lng' => 39.6401, 'media_type' => 'Billboards'],
        ['town' => 'Wajir', 'county' => 'Wajir', 'lat' => 1.7471, 'lng' => 40.0573, 'media_type' => 'Street Light Ads'],
        ['town' => 'Marsabit', 'county' => 'Marsabit', 'lat' => 2.3347, 'lng' => 37.9909, 'media_type' => 'Street Light Ads'],
        ['town' => 'Meru', 'county' => 'Meru', 'lat' => 0.0470, 'lng' => 37.6496, 'media_type' => 'Street Light Ads'],
        ['town' => 'Embu', 'county' => 'Embu', 'lat' => -0.5397, 'lng' => 37.4574, 'media_type' => 'Pavement Ads'],
        ['town' => 'Machakos', 'county' => 'Machakos', 'lat' => -1.5177, 'lng' => 37.2634, 'media_type' => 'Street Light Ads'],
        ['town' => 'Kitui', 'county' => 'Kitui', 'lat' => -1.3667, 'lng' => 38.0167, 'media_type' => 'Street Light Ads'],
        ['town' => 'Kitengela', 'county' => 'Kajiado', 'lat' => -1.4761, 'lng' => 36.9612, 'media_type' => 'Billboards'],
        ['town' => 'Kajiado', 'county' => 'Kajiado', 'lat' => -1.8511, 'lng' => 36.7768, 'media_type' => 'Street Light Ads'],
        ['town' => 'Kilifi', 'county' => 'Kilifi', 'lat' => -3.6310, 'lng' => 39.8499, 'media_type' => 'Street Light Ads'],
        ['town' => 'Nairobi', 'county' => 'Nairobi', 'lat' => -1.2864, 'lng' => 36.8172, 'media_type' => 'Billboards'],
        ['town' => 'Mombasa', 'county' => 'Mombasa', 'lat' => -4.0435, 'lng' => 39.6682, 'media_type' => 'Billboards'],
        ['town' => 'Kwale', 'county' => 'Kwale', 'lat' => -4.1737, 'lng' => 39.4521, 'media_type' => 'Pavement Ads'],
        ['town' => 'Voi', 'county' => 'Taita Taveta', 'lat' => -3.3960, 'lng' => 38.5561, 'media_type' => 'Street Light Ads'],
        ['town' => 'Laikipia', 'county' => 'Laikipia', 'lat' => 0.3667, 'lng' => 36.7833, 'media_type' => 'Street Light Ads'],
        ['town' => 'Nyamira', 'county' => 'Nyamira', 'lat' => -0.5633, 'lng' => 34.9358, 'media_type' => 'Street Light Ads'],
        ['town' => 'Keroka', 'county' => 'Nyamira', 'lat' => -0.7758, 'lng' => 34.9461, 'media_type' => 'Street Light Ads'],
    ],
    'why_choose_us' => [
        ['title' => 'Strategic Locations', 'detail' => 'High-traffic roads, CBD corridors, interchanges, and urban centers selected for repeat visibility.'],
        ['title' => 'Repetitive Visibility', 'detail' => 'Street-light sequencing creates consistent message recall for daily commuters.'],
        ['title' => 'Fast Campaign Deployment', 'detail' => 'Rapid scheduling and installation from approved artworks to campaign go-live.'],
        ['title' => 'Cost Effective Reach', 'detail' => 'Affordable reach compared with larger-format-only media plans.'],
        ['title' => 'Maintenance Support', 'detail' => 'Routine cleaning and maintenance with quick replacement for damaged units.'],
        ['title' => 'Flexible Planning', 'detail' => 'Town, county, and road-specific targeting based on campaign priorities.'],
    ],
    'industries' => ['Banking', 'Hospitality', 'Petroleum', 'FMCG', 'Automotive', 'Real Estate', 'Healthcare', 'Retail', 'Manufacturing'],
    'clients' => ['KFC', 'Dr Mattress', 'KenJap', 'Wasili', 'Ole Ken Hotel', 'Domaine Kenya'],
    'operational_commitments' => [
        'Quality installation standards',
        'Regulatory and council compliance support',
        'Professional and experienced field teams',
        'Timely delivery and launch execution',
        'Campaign maintenance and reporting support',
        'Safety-first site operations',
    ],
    'rates' => [
        ['duration' => '1 Month', 'printing' => 'KES 4,000', 'flighting' => 'KES 10,000', 'total' => 'KES 14,000'],
        ['duration' => '3 Months', 'printing' => 'KES 4,000', 'flighting' => 'KES 8,000', 'total' => 'KES 12,000'],
        ['duration' => '6 Months +', 'printing' => 'KES 4,000', 'flighting' => 'KES 6,000', 'total' => 'KES 10,000'],
    ],
    'faqs' => [
        ['question' => 'Artwork changes?', 'answer' => 'You only pay for printing when changing artwork.' ],
        ['question' => 'Hit / spoilt boxes?', 'answer' => 'We replace spoilt boxes as soon as possible and compensate with additional running days.' ],
        ['question' => 'Prolonging a campaign?', 'answer' => 'Campaign duration can be extended based on site availability and updated scheduling.' ],
        ['question' => 'Sites that we do not cover?', 'answer' => 'We check availability and re-target to the nearest active coverage site as quickly as possible.' ],
        ['question' => 'Thinking billboards?', 'answer' => 'We suggest billboard options to complement street light box reach and negotiate partner rates on your behalf.' ],
    ],
    'contacts' => [
        'email' => 'info@effectivemedia.co.ke',
        'website' => 'www.effectivemedia.co.ke',
        'phones' => ['0725 646 642', '0780 646 642', '0792 552 907'],
        'office' => 'Nakuru Office, Kenyatta Avenue, Vickers House, 1st Floor',
    ],
    /** Optional public profile URLs — set in .env to show footer social icons. */
    'social' => [
        'facebook' => env('EM_SOCIAL_FACEBOOK'),
        'instagram' => env('EM_SOCIAL_INSTAGRAM'),
        'linkedin' => env('EM_SOCIAL_LINKEDIN'),
    ],
    'portfolio' => [
        ['title' => 'Street Light Box Campaign', 'client' => 'Corporate Client', 'location' => 'West Road Nakuru', 'media_type' => 'Street Light Ads', 'caption' => 'Back-to-back street pole kiosk branding along high-traffic urban roads.', 'image' => 'profile-page-2.jpg'],
        ['title' => 'City Road Visibility Push', 'client' => 'Brand Campaign', 'location' => 'Kenyatta Avenue Nakuru', 'media_type' => 'Street Light Ads', 'caption' => 'Repetitive street light box placement to boost daily commuter visibility.', 'image' => 'profile-page-3.jpg'],
        ['title' => 'CBD Awareness Campaign', 'client' => 'Retail Campaign', 'location' => 'Nakuru CBD', 'media_type' => 'Pavement Ads', 'caption' => 'Compact formats positioned for consistent in-town brand recall.', 'image' => 'profile-page-4.jpg'],
        ['title' => 'Transit Route Branding', 'client' => 'Service Brand', 'location' => 'Naivasha CBD', 'media_type' => 'Billboards', 'caption' => 'Route-based media support integrated with street light placements.', 'image' => 'profile-page-5.jpg'],
        ['title' => 'Regional Market Entry', 'client' => 'Growth Brand', 'location' => 'Kisumu CBD', 'media_type' => 'Street Light Ads', 'caption' => 'Town-level expansion with repetitive placement strategy.', 'image' => 'profile-page-6.jpg'],
        ['title' => 'Highway Interchange Media', 'client' => 'National Brand', 'location' => 'Gilgil', 'media_type' => 'Activations', 'caption' => 'Strategic coverage near interchanges for high visibility.', 'image' => 'profile-page-7.jpg'],
    ],
];
